#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRG2_20232_P7_1_90
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="P5_90")]
	public partial class LINQ_0320230090DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertms_supplier(ms_supplier instance);
    partial void Updatems_supplier(ms_supplier instance);
    partial void Deletems_supplier(ms_supplier instance);
    #endregion
		
		public LINQ_0320230090DataContext() : 
				base(global::PRG2_20232_P7_1_90.Properties.Settings.Default.P5_90ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320230090DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320230090DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320230090DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320230090DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ms_supplier> ms_suppliers
		{
			get
			{
				return this.GetTable<ms_supplier>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ms_supplier")]
	public partial class ms_supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_supplier;
		
		private string _nama_supplier;
		
		private string _telp;
		
		private string _alamat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_supplierChanging(string value);
    partial void Onid_supplierChanged();
    partial void Onnama_supplierChanging(string value);
    partial void Onnama_supplierChanged();
    partial void OntelpChanging(string value);
    partial void OntelpChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public ms_supplier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_supplier", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_supplier
		{
			get
			{
				return this._id_supplier;
			}
			set
			{
				if ((this._id_supplier != value))
				{
					this.Onid_supplierChanging(value);
					this.SendPropertyChanging();
					this._id_supplier = value;
					this.SendPropertyChanged("id_supplier");
					this.Onid_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_supplier", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nama_supplier
		{
			get
			{
				return this._nama_supplier;
			}
			set
			{
				if ((this._nama_supplier != value))
				{
					this.Onnama_supplierChanging(value);
					this.SendPropertyChanging();
					this._nama_supplier = value;
					this.SendPropertyChanged("nama_supplier");
					this.Onnama_supplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telp", DbType="VarChar(13)")]
		public string telp
		{
			get
			{
				return this._telp;
			}
			set
			{
				if ((this._telp != value))
				{
					this.OntelpChanging(value);
					this.SendPropertyChanging();
					this._telp = value;
					this.SendPropertyChanged("telp");
					this.OntelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
